name: projetsndcp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  google_sign_in: ^6.0.1
  flutter_facebook_auth: ^6.0.0
  checkmark: ^0.0.2+1
  equatable: ^2.0.7
  image_picker: ^1.2.1
  google_maps_flutter: ^2.15.0
  geolocator: ^14.0.2
  percent_indicator: ^4.2.3
  timelines_plus: ^2.0.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.4
  share_plus: ^12.0.2
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
     - images/Logo2.png
     - images/google.png
     - images/facebook.png
     - images/serdina.jpg
     - images/sea.png
     - images/fish1.png
     - images/fish2.png
     - images/fish3.jpg
     - images/grey.jpg
     - images/boat.svg
     - images/vitirinaire.svg
     - images/consumer.svg
     - images/map.png
     - images/logoPolice.png
     - images/Logo1.png
     - images/Bahr.png


  fonts:
   - family: Inter
     fonts:
       - asset: fonts/Inter-VariableFont_opsz,wght.ttf
   - family: work sanc
     fonts:
       - asset: fonts/WorkSans-VariableFont_wght.ttf 
